#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export OT_TARGET_ARCH="armv7a"
export ANDROID_EABI_OT="arm-linux-androideabi"
export ANDROID_EABI_OT_OVERRIDE="armv7-none-linux-androideabi"
export ANDROID_GCC_VERSION_OT="4.9"
export ABI=armeabi-v7a
export ANDROID_STL=libc++
export ANDROID_STL_LIB="c++_shared"
export ANDROID_STL_TOOLCHAIN_LIB="${CXXSTL_LIB}/armv7-a/lib${ANDROID_STL_LIB}.so"
export ARCH_HOST_DUET_OT="arm-linux"
export ANDROID_ARCH_NDK_OT="arm"
export ANDROID_ARCH_OT=arch-arm

export CFLAGS_ARM7="-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb"
export CXXFLAGS_ARM7="-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb"
export LDFLAGS_ARM7="-march=armv7-a"

source ~/bin/common-variables
source ~/bin/paths_android
source ~/bin/versions

export CFLAGS_OT="${CFLAGS_ARM7} ${CFLAGS_COMMON}"
export CXXFLAGS_OT="${CXXFLAGS_ARM7} ${CXXFLAGS_COMMON}"
export LDFLAGS_OT="${LDFLAGS_ARM7} ${LDFLAGS_COMMON}"
