#!/bin/bash

export OT_TARGET_ARCH="x86_64"
export OT_NDK_TYPE="android-ndk-r15c"
export ANDROID_EABI_OT="x86_64-linux-android"
export ANDROID_GCC_VERSION_OT="4.9"
export ABI=x86_64
export ANDROID_STL=libc++
export ANDROID_STL_LIB="c++_shared"
export ARCH_HOST_DUET_OT="x86_64-linux"
export ANDROID_ARCH_NDK_OT="x86_64"
export ANDROID_ARCH_OT=arch-x86_64

export CFLAGS_X86="-march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel"
export CXXFLAGS_X86="-march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel"
export LDFLAGS_X86="-march=x86-64"

source ~/bin/common-variables
source ~/bin/paths_android
source ~/bin/versions

export CFLAGS_OT="${CFLAGS_X86} ${CFLAGS_COMMON}"
export CXXFLAGS_OT="${CXXFLAGS_X86} ${CXXFLAGS_COMMON}"
export LDFLAGS_OT="${LDFLAGS_X86} ${LDFLAGS_COMMON}"
