#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export OT_TARGET_ARCH="x86"
export ANDROID_EABI_OT="i686-linux-android"
export ANDROID_EABI_OT_OVERRIDE="i686-none-linux-androideabi"
export ANDROID_GCC_VERSION_OT="4.9"
export ABI=x86
export ANDROID_STL=libc++
export ANDROID_STL_LIB="c++_shared"
export ARCH_HOST_DUET_OT="i686-linux"
export ANDROID_ARCH_NDK_OT="x86"
export ANDROID_ARCH_OT=arch-x86
export ANDROID_STL_TOOLCHAIN_LIB="${CXXSTL_LIB}/lib${ANDROID_STL_LIB}.so"

export CFLAGS_X86="-mtune=atom -mstackrealign -msse3 -mfpmath=sse -m32"
export CXXFLAGS_X86="-mtune=atom -mstackrealign -msse3 -mfpmath=sse -m32"
export LDFLAGS_X86=""

source ~/bin/common-variables
source ~/bin/paths_android
source ~/bin/versions

export CFLAGS_OT="${CFLAGS_X86} ${CFLAGS_COMMON}"
export CXXFLAGS_OT="${CXXFLAGS_X86} ${CXXFLAGS_COMMON}"
export LDFLAGS_OT="${LDFLAGS_X86} ${LDFLAGS_COMMON}"
