#!/bin/bash

export OT_TARGET_ARCH="x86"
export ANDROID_EABI_OT="i686-linux-android"
export ANDROID_GCC_VERSION_OT="4.9"
export ABI=x86
export ANDROID_STL=libc++
export ANDROID_STL_LIB="c++_shared"
export ARCH_HOST_DUET_OT="i686-linux"
export ANDROID_ARCH_NDK_OT="x86"
export ANDROID_ARCH_OT=arch-x86

export CFLAGS_X86="-mtune=atom -mstackrealign -msse3 -mfpmath=sse -m32"
export CXXFLAGS_X86="-mtune=atom -mstackrealign -msse3 -mfpmath=sse -m32"
export LDFLAGS_X86=""

source ~/bin/common-variables
source ~/bin/paths_android
source ~/bin/versions

export CFLAGS_OT="${CFLAGS_X86} ${CFLAGS_COMMON}"
export CXXFLAGS_OT="${CXXFLAGS_X86} ${CXXFLAGS_COMMON}"
export LDFLAGS_OT="${LDFLAGS_X86} ${LDFLAGS_COMMON}"
