#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

source "${HOME}"/bin/functions
check_arch "${1}"
source "${HOME}"/bin/android-"${OT_ARCH}"

export LOCAL_SOURCE_DIR="${SRC_DIR}/${FOLDER_SODIUM_OT}"
export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_SODIUM_OT}"
export TOOLCHAIN_LIBRARY="libsodium.so"
export OUTPUT_LIBRARY="libsodium.so"

clean_directories "${LOCAL_BUILD_DIR}" "${LOCAL_SOURCE_DIR}" ""

set -e

create_directories "${LOCAL_SOURCE_DIR}" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"

git_clone_source "${SODIUM_VERSION_OT}" "${GIT_SODIUM_URL}" "${LOCAL_SOURCE_DIR}"

cd "${LOCAL_SOURCE_DIR}"
./autogen.sh

cd "${LOCAL_BUILD_DIR}"

"${LOCAL_SOURCE_DIR}"/configure --prefix="${SYSROOT}/usr" \
 --host="${ANDROID_EABI_OT}" \
 --with-sysroot="${SYSROOT}" \
 --disable-static \
 --enable-shared \
 --with-pthreads \
 --disable-asm \
 --disable-soname-versions \
  CPPFLAGS="-I${OUTPUT_DIR}/include" \
  CFLAGS="${CFLAGS_OT}" \
  CXXFLAGS="${CXXFLAGS_OT}" \
  LDFLAGS="${LDFLAGS_OT} -L${CXXSTL_LIB} -L${OUTPUT_DIR}/lib" \
  LIBS="-l${ANDROID_STL_LIB}"

make "${OT_MAKE_OPTS}"
make install
cp "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"
