#!/bin/bash

source "${HOME}"/bin/android-armv7a

export LOCAL_SOURCE_DIR="${SRC_DIR}/${FOLDER_OPENTXS_PROTO_OT}"
export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_OPENTXS_PROTO_OT}"
export TOOLCHAIN_LIBRARY="libopentxs-proto.so"
export OUTPUT_LIBRARY="libopentxs-proto.so"

clean_directories "${LOCAL_BUILD_DIR}" "${LOCAL_SOURCE_DIR}" ""

set -e

create_directories "${LOCAL_SOURCE_DIR}" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"
git_clone_source "${OPENTXS_PROTO_VERSION_OT}" "${GIT_OPENTXS_PROTO_URL}" "${LOCAL_SOURCE_DIR}"

sed -i "s/list(APPEND OPENTXS_SYSTEM_LIBRARIES rt)/#list(APPEND OPENTXS_SYSTEM_LIBRARIES rt)/" "${LOCAL_SOURCE_DIR}"/CMakeLists.txt

# A hack. We're overwriting the standalone toolchain's protoc
# with the system protoc (so it can run during cross-compile.)
# It will be better to just find anyplace we actually use protoc
# and give it the path there, rather than overwriting the standalone
# toolchain's copy. It may not be so simple however, and we'll figure
# it out later. This works for now.
cp "${PROTOC_LOCATION_BUILD_MACHINE_OT}" "${TOOLCHAIN_USR_OT}/bin/protoc"

cd "${LOCAL_BUILD_DIR}"

# -DCMAKE_SYSTEM_PREFIX_PATH="${TOOLCHAIN_SYSROOT_OT}" \

cmake \
 -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}" \
 -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
 -DCMAKE_CXX_FLAGS="" \
 -DUSE_CCACHE=no \
 -DCMAKE_TOOLCHAIN_FILE="${ANDROID_TOOLCHAIN_FILE}" \
 -DCMAKE_INSTALL_PREFIX="${TOOLCHAIN_USR_OT}" \
 -DJAVA=ON \
 -DProtobuf_LIBRARIES="${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/libprotobuf-lite.so" \
 -DProtobuf_LITE_LIBRARY="${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/libprotobuf-lite.so" \
 -DProtobuf_INCLUDE_DIR="${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}" \
 "${LOCAL_SOURCE_DIR}"

cmake \
 -DCMAKE_C_COMPILER="${CMAKE_C_COMPILER}" \
 -DCMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER}" \
 -DCMAKE_CXX_FLAGS="" \
 -DUSE_CCACHE=no \
 -DCMAKE_TOOLCHAIN_FILE="${ANDROID_TOOLCHAIN_FILE}" \
 -DCMAKE_INSTALL_PREFIX="${TOOLCHAIN_USR_OT}" \
 -DJAVA=ON \
 -DProtobuf_LIBRARIES="${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/libprotobuf-lite.so" \
 -DProtobuf_LITE_LIBRARY="${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/libprotobuf-lite.so" \
 -DProtobuf_INCLUDE_DIR="${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}" \
 "${LOCAL_SOURCE_DIR}"

make "${OT_MAKE_OPTS}"
make install

mkdir -p "${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}"
cp -R "${LOCAL_SOURCE_DIR}"/include/"${FOLDER_OPENTXS_PROTO_OT}" "${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}"
cp -R "${LOCAL_BUILD_DIR}"/src/"${FOLDER_OPENTXS_PROTO_OT}"/*.pb.h "${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}/${FOLDER_OPENTXS_PROTO_OT}/"

mkdir -p "${FINAL_OUTPUT_DIR_JAVA_OPENTXS_PROTO}"
cp "${TOOLCHAIN_USR_OT}/share/opentxs-proto/java/org/opentransactions/proto"/*.java "${FINAL_OUTPUT_DIR_JAVA_OPENTXS_PROTO}/"

cp "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"
rpl -R -e ".so.9" "_9.so" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"
