#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

source "${HOME}"/bin/functions
check_arch "${1}"
source "${HOME}"/bin/android-"${OT_ARCH}"

export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_SQLITE_OT}"
export ARCHIVE_FILE="${SRC_DIR}/sqlite3.zip"
export TOOLCHAIN_LIBRARY="libsqlite3.so"
export OUTPUT_LIBRARY="libsqlite3.so"

clean_directories "${LOCAL_BUILD_DIR}" "" "${ARCHIVE_FILE}"

set -e

create_directories "" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"
wget --output-document="${ARCHIVE_FILE}" "${WGET_SQLITE_URL}"
cd "${BUILD_DIR}"
cp "${ARCHIVE_FILE}" .
unzip -oq sqlite3.zip
rm -rf "${LOCAL_BUILD_DIR}"
mv "sqlite-amalgamation-${SQLITE_VERSION_OT}" "${LOCAL_BUILD_DIR}"

export CFLAGS="-O3 ${CFLAGS_OT}"
export LDFLAGS="${LDFLAGS_OT} -L${CXXSTL_LIB} -l${ANDROID_STL_LIB}"

"${CMAKE_C_COMPILER}" ${CFLAGS} "-I${CXXSTL_INCLUDE}" --sysroot="${SYSROOT}" -c "${LOCAL_BUILD_DIR}/sqlite3.c" -o "${LOCAL_BUILD_DIR}/sqlite3.o"
"${CMAKE_C_COMPILER}" ${LDFLAGS} -shared -o "${LOCAL_BUILD_DIR}/${TOOLCHAIN_LIBRARY}" "${LOCAL_BUILD_DIR}/sqlite3.o"

cp "${LOCAL_BUILD_DIR}"/sqlite3.h "${TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT}"
cp "${LOCAL_BUILD_DIR}/${TOOLCHAIN_LIBRARY}" "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}"
cp "${LOCAL_BUILD_DIR}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"
