#!/bin/bash

source "${HOME}"/bin/android-armv7a

export LOCAL_SOURCE_DIR="${SRC_DIR}/${FOLDER_SODIUM_OT}"
export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_SODIUM_OT}"
export ARCHIVE_FILE="${SRC_DIR}/sodium.tar.gz"
export TOOLCHAIN_LIBRARY="libsodium.so"
export OUTPUT_LIBRARY="libsodium.so"

clean_directories "${LOCAL_BUILD_DIR}" "${LOCAL_SOURCE_DIR}" "${ARCHIVE_FILE}"

set -e

create_directories "${LOCAL_SOURCE_DIR}" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"

wget_source "${ARCHIVE_FILE}" "${WGET_SODIUM_URL}" "${LOCAL_SOURCE_DIR}"

cd "${LOCAL_BUILD_DIR}"

"${LOCAL_SOURCE_DIR}"/configure --prefix="${SYSROOT}/usr" \
 --host="${ANDROID_EABI_OT}" \
 --with-sysroot="${SYSROOT}" \
 --disable-static \
 --enable-shared \
 --with-pthreads \
 --disable-asm \
 --disable-soname-versions \
  CPPFLAGS="-I${OUTPUT_DIR}/include" \
  CFLAGS="-MMD -MP -MF -fPIC -fexceptions -ffunction-sections -funwind-tables -fstack-protector -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -Wl,--fix-cortex-a8 -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security" \
  CXXFLAGS="-fPIC -frtti -fexceptions -ffunction-sections -funwind-tables -fstack-protector -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -Wl,--fix-cortex-a8 -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security" \
  LDFLAGS="-march=armv7-a -Wl,--fix-cortex-a8 -L${OUTPUT_DIR}/lib"

make "${OT_MAKE_OPTS}"
make install
cp "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"


