#!/bin/bash

source "${HOME}"/bin/android-armv7a

export LOCAL_SOURCE_DIR="${SRC_DIR}/${FOLDER_SECP256K1_OT}"
export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_SECP256K1_OT}"
export TOOLCHAIN_LIBRARY="libsecp256k1.so"
export OUTPUT_LIBRARY="libsecp256k1.so"

export CC_FOR_BUILD="${CC}"

clean_directories "${LOCAL_BUILD_DIR}" "${LOCAL_SOURCE_DIR}" ""

set -e

create_directories "" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"

git_clone_source "${SECP256K1_VERSION_OT}" "${GIT_SECP256K1_URL}" "${LOCAL_SOURCE_DIR}"

cd "${LOCAL_SOURCE_DIR}"
./autogen.sh

cd "${LOCAL_BUILD_DIR}"

"${LOCAL_SOURCE_DIR}"/configure \
 --prefix="${OUTPUT_DIR}" \
 --host="${ANDROID_EABI_OT}" \
 --with-sysroot="${SYSROOT}" \
 --disable-static \
 --enable-shared \
 --disable-openssl-tests \
 --enable-experimental \
 --disable-exhaustive-tests \
 --enable-module-ecdh \
 --enable-module-recovery \
 --disable-jni \
 --with-bignum=no \
 --with-asm=no \
  CPPFLAGS="-I${OUTPUT_DIR}/include" \
  CFLAGS="-MMD -MP -MF -fPIC -fexceptions -ffunction-sections -funwind-tables -fstack-protector -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -Wl,--fix-cortex-a8 -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security" \
  CXXFLAGS="-fPIC -frtti -fexceptions -ffunction-sections -funwind-tables -fstack-protector -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -mthumb -Wl,--fix-cortex-a8 -fomit-frame-pointer -fno-strict-aliasing -finline-limit=64 -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security" \
  LDFLAGS="-march=armv7-a -Wl,--fix-cortex-a8 -L${OUTPUT_DIR}/lib"

make "${OT_MAKE_OPTS}"
make install
cp "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"

