#!/bin/bash

source "${HOME}"/bin/android-x86

export LOCAL_SOURCE_DIR="${SRC_DIR}/${FOLDER_CZMQ_OT}"
export LOCAL_BUILD_DIR="${BUILD_DIR}/${FOLDER_CZMQ_OT}"
export TOOLCHAIN_LIBRARY="libczmq.so"
export OUTPUT_LIBRARY="libczmq.so"

export HOST="${ARCH_HOST_DUET_OT}"
export BUILD_MACHINE="${ALTERNATE_BUILDING_ON_MACHINE_TYPE}"

clean_directories "${LOCAL_BUILD_DIR}" "${LOCAL_SOURCE_DIR}" ""

set -e

create_directories "${LOCAL_SOURCE_DIR}" "${LOCAL_BUILD_DIR}" "${FINAL_OUTPUT_DIR_LIB_OT}"

git_clone_source "${CZMQ_VERSION_OT}" "${GIT_CZMQ_URL}" "${LOCAL_SOURCE_DIR}"
sed -i "s~uuid/uuid\.h~linux/uuid\.h~" "${LOCAL_SOURCE_DIR}"/configure.ac
sed -i "s~uuid/uuid\.h~linux/uuid\.h~" "${LOCAL_SOURCE_DIR}"/include/czmq_prelude.h

cd "${LOCAL_SOURCE_DIR}"
./autogen.sh

cd "${LOCAL_BUILD_DIR}"

"${LOCAL_SOURCE_DIR}"/configure \
 --prefix="${OUTPUT_DIR}" \
 --host="${ANDROID_EABI_OT}" \
 --with-docs=no \
 --disable-static \
 --enable-shared \
 --disable-zmakecert \
  CPPFLAGS="-I${CXXSTL_INCLUDE} -I${OUTPUT_DIR}/include" \
  CFLAGS="${CFLAGS_OT}" \
  CXXFLAGS="${CXXFLAGS_OT}" \
  LDFLAGS="${LDFLAGS_OT} -L${CXXSTL_LIB} -L${OUTPUT_DIR}/lib" \
  LIBS="-l${ANDROID_STL_LIB}"
make "${OT_MAKE_OPTS}"
make install
cp "${TOOLCHAIN_SYSROOT_LIB_DIR_OT}/${TOOLCHAIN_LIBRARY}" "${FINAL_OUTPUT_DIR_LIB_OT}/${OUTPUT_LIBRARY}"

