#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

source "${HOME}"/bin/functions
check_arch "${1}"
source "${HOME}"/bin/android-"${OT_ARCH}"

set -e

rm -rf "${SRC_DIR}" "${BUILD_DIR}" "${ANDROID_STANDALONE_TOOLCHAIN}" "${FINAL_OUTPUT_DIR_LIB_OT}"
cd "${HOME}/bin"

./create-toolchain "${1}"

# no extra dependencies
./build_secp256k1 "${1}"

# no extra dependencies
./build_protobuf "${1}"

# no extra dependencies
./build_openssl "${1}"

# no extra dependencies
./build_sqlite3 "${1}"

# no extra dependencies
./build_sodium "${1}"

# depends on sodium
./build_zeromq "${1}"

#########################################################################

./build_opentxs-proto "${1}"
./build_opentxs "${1}"
