#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export OT_NDK_TYPE="android-ndk-r16"
export ANDROID_NDK_ROOT="/usr/local/share/ndk/${OT_NDK_TYPE}"
export ANDROID_LEVEL_OT="21"
export OPENSSL_ANDROID_API_OT="android-${ANDROID_LEVEL_OT}"
export ANDROID_STANDALONE_TOOLCHAIN="${HOME}/toolchain/${OT_NDK_TYPE}/${OT_TARGET_ARCH}"
export TOOLCHAIN_SYSROOT_OT="${ANDROID_STANDALONE_TOOLCHAIN}"/sysroot
export TOOLCHAIN_USR_OT="${TOOLCHAIN_SYSROOT_OT}"/usr
export TOOLCHAIN_SYSROOT_INCLUDE_DIR_OT="${TOOLCHAIN_USR_OT}"/include
export TOOLCHAIN_SYSROOT_LIB_DIR_OT="${TOOLCHAIN_USR_OT}"/lib
export SRC_DIR="${HOME}/src/${OT_NDK_TYPE}/${OT_TARGET_ARCH}"
export BUILD_DIR="${HOME}/build/${OT_NDK_TYPE}/${OT_TARGET_ARCH}"
export OT_MAKE_OPTS="-j8"
export FINAL_OUTPUT_DIR_OT="${HOME}/install/"
export FINAL_OUTPUT_DIR_LIB_OT="${FINAL_OUTPUT_DIR_OT}/android_libs/${ABI}"
export FINAL_OUTPUT_DIR_JAVA_OPENTXS_PROTO="${FINAL_OUTPUT_DIR_OT}/java/org/opentransactions/proto"
export FINAL_OUTPUT_DIR_JAVA_OPENTXS_OT="${FINAL_OUTPUT_DIR_OT}/java/org/opentransactions/otapi"
export BUILDING_ON_MACHINE_TYPE="linux-x86_64"
export ALTERNATE_BUILDING_ON_MACHINE_TYPE="x86_64-linux"
export PROTOC_LOCATION_BUILD_MACHINE_OT="/usr/bin/protoc"
export ANDROID_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake"
export CFLAGS_COMMON="-MP -MF -fPIC -fexceptions -ffunction-sections -funwind-tables -fstack-protector -fomit-frame-pointer -fno-strict-aliasing -DANDROID -Wformat -Werror=format-security"
export CXXFLAGS_COMMON="-fPIC -frtti -fexceptions -ffunction-sections -funwind-tables -fstack-protector -fomit-frame-pointer -fno-strict-aliasing -DANDROID -Wformat -Werror=format-security"
export LDFLAGS_COMMON=""
export SYSROOT="${TOOLCHAIN_SYSROOT_OT}"
export OUTPUT_DIR="${SYSROOT}/usr"
