#!/bin/bash

source "${HOME}"/bin/android-armv7a

set -e

if [ -e "${ANDROID_STANDALONE_TOOLCHAIN}" ] ; then
	rm -rf "${ANDROID_STANDALONE_TOOLCHAIN}"
fi

mkdir -p "${HOME}/toolchain"
cd "${ANDROID_NDK_ROOT}"
build/tools/make_standalone_toolchain.py --api "${ANDROID_LEVEL_OT}" --stl "${ANDROID_STL}" --arch "${ANDROID_ARCH_NDK_OT}" --install-dir "${ANDROID_STANDALONE_TOOLCHAIN}" --unified-headers
