#!/bin/bash

source "${HOME}"/bin/android-armv7a

OT_DIR="${SRC_DIR}/${FOLDER_OPENTXS_OT}"
OT_VERSION="$(git -C ${OT_DIR} describe)"

STASH_WALLET="/home/colin/stash-wallet"
JNILIBS="${STASH_WALLET}/app/src/main/jniLibs/"
JAVA_FILES="${STASH_WALLET}/app/src/main/java/"

git -C "${STASH_WALLET}" remote update -p
git -C "${STASH_WALLET}" checkout master
git -C "${STASH_WALLET}" reset --hard origin/master
rsync -avX --delete "${FINAL_OUTPUT_DIR_OT}/android_libs/" "${JNILIBS}"
rsync -avX "${FINAL_OUTPUT_DIR_OT}/java/" "${JAVA_FILES}"
git -C "${STASH_WALLET}" add .
git -C "${STASH_WALLET}" commit -a -S -m "Update for opentxs-${OT_VERSION}"
#git -C "${STASH_WALLET}" push --force build master
git -C "${STASH_WALLET}" push origin master
