#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export TOOCHAIN_BIN_OT="${ANDROID_STANDALONE_TOOLCHAIN}/bin"
export PATH="${TOOCHAIN_BIN_OT}:${PATH}"
export CMAKE_C_COMPILER="${TOOCHAIN_BIN_OT}/${ANDROID_EABI_OT}-clang"
export CMAKE_CXX_COMPILER="${TOOCHAIN_BIN_OT}/${ANDROID_EABI_OT}-clang++"
export CC="${CMAKE_C_COMPILER} --sysroot ${SYSROOT}"
export CXX="${CMAKE_CXX_COMPILER} --sysroot ${SYSROOT}"
export CXXSTL_INCLUDE="${ANDROID_STANDALONE_TOOLCHAIN}/include/c++/4.9.x/"
export CXXSTL_LIB="${ANDROID_STANDALONE_TOOLCHAIN}/${ANDROID_EABI_OT}/lib"
