#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export OPENSSL_VERSION_OT="1.0.2o"
export OPENTXS_VERSION_OT="android"

export FOLDER_OPENSSL_OT="openssl"
export WGET_OPENSSL_URL="http://www.openssl.org/source/${FOLDER_OPENSSL_OT}-${OPENSSL_VERSION_OT}.tar.gz"
export FOLDER_OPENTXS_OT="opentxs"
export GIT_OPENTXS_URL="https://github.com/Stash-Crypto/opentxs.git"
