#!/bin/bash
# Copyright (c) 2017 The Open-Transactions developers
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

export PROTOBUF_VERSION_OT="2.6.1"
export SODIUM_VERSION_OT="1.0.16"
export ZEROMQ_VERSION_OT="v4.2.5"
export SECP256K1_VERSION_OT="master"
export OPENSSL_VERSION_OT="1.0.2o"
export SQLITE_BRANCH_OT="master"
export SQLITE_YEAR_OT="2017"
export SQLITE_VERSION_OT="3200100"
export OPENTXS_PROTO_VERSION_OT="experimental"
export OPENTXS_VERSION_OT="experimental"

export FOLDER_PROTOBUF_OT="protobuf"
#export WGET_PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION_OT}/${FOLDER_PROTOBUF_OT}-cpp-${PROTOBUF_VERSION_OT}.tar.gz"
export WGET_PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION_OT}/${FOLDER_PROTOBUF_OT}-${PROTOBUF_VERSION_OT}.tar.gz"
export FOLDER_SODIUM_OT="libsodium"
export GIT_SODIUM_URL="https://github.com/jedisct1/libsodium"
export FOLDER_ZMQ_OT="zeromq"
export GIT_ZMQ_URL="https://github.com/zeromq/libzmq.git"
export FOLDER_SECP256K1_OT="secp256k1"
export GIT_SECP256K1_URL="https://github.com/bitcoin-core/secp256k1.git"
export FOLDER_OPENSSL_OT="openssl"
export WGET_OPENSSL_URL="http://www.openssl.org/source/${FOLDER_OPENSSL_OT}-${OPENSSL_VERSION_OT}.tar.gz"
export FOLDER_SQLITE_OT="sqlite3"
export WGET_SQLITE_URL="http://www.sqlite.org/${SQLITE_YEAR_OT}/sqlite-amalgamation-${SQLITE_VERSION_OT}.zip"
export FOLDER_OPENTXS_PROTO_OT="opentxs-proto"
export GIT_OPENTXS_PROTO_URL="https://github.com/Stash-Crypto/opentxs-proto.git"
export FOLDER_OPENTXS_OT="opentxs"
export GIT_OPENTXS_URL="https://github.com/Stash-Crypto/opentxs.git"

